//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuzDelSaber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdProyectoColegioEntities : DbContext
    {
        public bdProyectoColegioEntities()
            : base("name=bdProyectoColegioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAlumno> tblAlumno { get; set; }
        public virtual DbSet<tblAsignatura> tblAsignatura { get; set; }
        public virtual DbSet<tblBimestre> tblBimestre { get; set; }
        public virtual DbSet<tblDocente> tblDocente { get; set; }
        public virtual DbSet<tblGrado> tblGrado { get; set; }
        public virtual DbSet<tblGradoInstruccion> tblGradoInstruccion { get; set; }
        public virtual DbSet<tblNotas> tblNotas { get; set; }
    }
}
