//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuzDelSaber
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAlumno()
        {
            this.tblNotas = new HashSet<tblNotas>();
        }
    
        public string DNI { get; set; }
        public string nombresAlumno { get; set; }
        public string apellidoPaternoAlumno { get; set; }
        public string apellidoMaternoAlumno { get; set; }
        public string genero { get; set; }
        public string Apoderado { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string codiGrado { get; set; }
        public string idGI { get; set; }
    
        public virtual tblGrado tblGrado { get; set; }
        public virtual tblGradoInstruccion tblGradoInstruccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotas> tblNotas { get; set; }
    }
}
