//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuzDelSaber
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAsignatura()
        {
            this.tblNotas = new HashSet<tblNotas>();
        }
    
        public string codiAsignatura { get; set; }
        public string nomAsignatura { get; set; }
        public string descAsignatura { get; set; }
        public Nullable<byte> idDocente { get; set; }
        public string idGI { get; set; }
    
        public virtual tblDocente tblDocente { get; set; }
        public virtual tblGradoInstruccion tblGradoInstruccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotas> tblNotas { get; set; }
    }
}
