//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuzDelSaber
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGrado()
        {
            this.tblAlumno = new HashSet<tblAlumno>();
        }
    
        public string codiGrado { get; set; }
        public string grado { get; set; }
        public string idGI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAlumno> tblAlumno { get; set; }
        public virtual tblGradoInstruccion tblGradoInstruccion { get; set; }
    }
}
