//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuzDelSaber
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotas
    {
        public int idRegistro { get; set; }
        public string DNI { get; set; }
        public string idBimestre { get; set; }
        public string codiAsignatura { get; set; }
        public int criterio1 { get; set; }
        public int criterio2 { get; set; }
        public int criterio3 { get; set; }
        public int criterio4 { get; set; }
        public int Promedio { get; set; }
        public string Comportamiento { get; set; }
    
        public virtual tblAlumno tblAlumno { get; set; }
        public virtual tblAsignatura tblAsignatura { get; set; }
        public virtual tblBimestre tblBimestre { get; set; }
    }
}
